/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZplConverterRouteImport } from './routes/zpl-converter'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as MarketplaceSlugIndexRouteImport } from './routes/marketplace.$slug.index'
import { Route as MarketplaceSlugProcessarRouteImport } from './routes/marketplace.$slug.processar'
import { Route as MarketplaceSlugPendenciasRouteImport } from './routes/marketplace.$slug.pendencias'
import { Route as MarketplaceSlugHistoricoRouteImport } from './routes/marketplace.$slug.historico'

const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZplConverterRoute = ZplConverterRouteImport.update({
  id: '/zpl-converter',
  path: '/zpl-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/marketplace/$slug',
  path: '/marketplace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugIndexRoute = MarketplaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceSlugRoute,
} as any)
const MarketplaceSlugProcessarRoute =
  MarketplaceSlugProcessarRouteImport.update({
    id: '/processar',
    path: '/processar',
    getParentRoute: () => MarketplaceSlugRoute,
  } as any)
const MarketplaceSlugPendenciasRoute =
  MarketplaceSlugPendenciasRouteImport.update({
    id: '/pendencias',
    path: '/pendencias',
    getParentRoute: () => MarketplaceSlugRoute,
  } as any)
const MarketplaceSlugHistoricoRoute =
  MarketplaceSlugHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => MarketplaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/zpl-converter': typeof ZplConverterRoute
  '/marketplace/$slug': typeof MarketplaceSlugRouteWithChildren
  '/marketplace/$slug/historico': typeof MarketplaceSlugHistoricoRoute
  '/marketplace/$slug/pendencias': typeof MarketplaceSlugPendenciasRoute
  '/marketplace/$slug/processar': typeof MarketplaceSlugProcessarRoute
  '/marketplace/$slug/': typeof MarketplaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/zpl-converter': typeof ZplConverterRoute
  '/marketplace/$slug/historico': typeof MarketplaceSlugHistoricoRoute
  '/marketplace/$slug/pendencias': typeof MarketplaceSlugPendenciasRoute
  '/marketplace/$slug/processar': typeof MarketplaceSlugProcessarRoute
  '/marketplace/$slug': typeof MarketplaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/zpl-converter': typeof ZplConverterRoute
  '/marketplace/$slug': typeof MarketplaceSlugRouteWithChildren
  '/marketplace/$slug/historico': typeof MarketplaceSlugHistoricoRoute
  '/marketplace/$slug/pendencias': typeof MarketplaceSlugPendenciasRoute
  '/marketplace/$slug/processar': typeof MarketplaceSlugProcessarRoute
  '/marketplace/$slug/': typeof MarketplaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/zpl-converter'
    | '/marketplace/$slug'
    | '/marketplace/$slug/historico'
    | '/marketplace/$slug/pendencias'
    | '/marketplace/$slug/processar'
    | '/marketplace/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/zpl-converter'
    | '/marketplace/$slug/historico'
    | '/marketplace/$slug/pendencias'
    | '/marketplace/$slug/processar'
    | '/marketplace/$slug'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/zpl-converter'
    | '/marketplace/$slug'
    | '/marketplace/$slug/historico'
    | '/marketplace/$slug/pendencias'
    | '/marketplace/$slug/processar'
    | '/marketplace/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ZplConverterRoute: typeof ZplConverterRoute
  MarketplaceSlugRoute: typeof MarketplaceSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zpl-converter': {
      id: '/zpl-converter'
      path: '/zpl-converter'
      fullPath: '/zpl-converter'
      preLoaderRoute: typeof ZplConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/marketplace/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug/': {
      id: '/marketplace/$slug/'
      path: '/'
      fullPath: '/marketplace/$slug/'
      preLoaderRoute: typeof MarketplaceSlugIndexRouteImport
      parentRoute: typeof MarketplaceSlugRoute
    }
    '/marketplace/$slug/processar': {
      id: '/marketplace/$slug/processar'
      path: '/processar'
      fullPath: '/marketplace/$slug/processar'
      preLoaderRoute: typeof MarketplaceSlugProcessarRouteImport
      parentRoute: typeof MarketplaceSlugRoute
    }
    '/marketplace/$slug/pendencias': {
      id: '/marketplace/$slug/pendencias'
      path: '/pendencias'
      fullPath: '/marketplace/$slug/pendencias'
      preLoaderRoute: typeof MarketplaceSlugPendenciasRouteImport
      parentRoute: typeof MarketplaceSlugRoute
    }
    '/marketplace/$slug/historico': {
      id: '/marketplace/$slug/historico'
      path: '/historico'
      fullPath: '/marketplace/$slug/historico'
      preLoaderRoute: typeof MarketplaceSlugHistoricoRouteImport
      parentRoute: typeof MarketplaceSlugRoute
    }
  }
}

interface MarketplaceSlugRouteChildren {
  MarketplaceSlugHistoricoRoute: typeof MarketplaceSlugHistoricoRoute
  MarketplaceSlugPendenciasRoute: typeof MarketplaceSlugPendenciasRoute
  MarketplaceSlugProcessarRoute: typeof MarketplaceSlugProcessarRoute
  MarketplaceSlugIndexRoute: typeof MarketplaceSlugIndexRoute
}

const MarketplaceSlugRouteChildren: MarketplaceSlugRouteChildren = {
  MarketplaceSlugHistoricoRoute: MarketplaceSlugHistoricoRoute,
  MarketplaceSlugPendenciasRoute: MarketplaceSlugPendenciasRoute,
  MarketplaceSlugProcessarRoute: MarketplaceSlugProcessarRoute,
  MarketplaceSlugIndexRoute: MarketplaceSlugIndexRoute,
}

const MarketplaceSlugRouteWithChildren = MarketplaceSlugRoute._addFileChildren(
  MarketplaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ZplConverterRoute: ZplConverterRoute,
  MarketplaceSlugRoute: MarketplaceSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
